### ISSUE TITLE
配置基本一致，没更换wifi模块，通过三方工具，intel 的 wifi 可以联网使用了。但是声卡还是没有声音，不晓得大哥后续会考虑解决声卡问题不？

### ISSUE THREAD

**Issue by fengcms** [fzlee/B460M-ITX-AC-EFI#1]
通过三方工具，intel 的 wifi 可以联网使用了。但是声卡还是没有声音，不晓得大哥后续会考虑解决声卡问题不？

**Comment by fzlee** [comment]
intel wifi稳定吗？ 貌似开关wifi需要用专门的工具？ 

声卡比较头疼， 尝试过几种方法， 还没搞定。 目前也没有看到成功的例子

**Comment by fzlee** [comment]
intel wifi稳定吗？ 貌似开关wifi需要用专门的工具？ 

声卡比较头疼， 尝试过几种方法， 还没搞定。 目前也没有看到成功的例子

**Comment by fzlee** [comment]
intel wifi稳定吗？ 貌似开关wifi需要用专门的工具？ 

声卡比较头疼， 尝试过几种方法， 还没搞定。 目前也没有看到成功的例子

**Comment by fzlee** [comment]
intel wifi稳定吗？ 貌似开关wifi需要用专门的工具？ 

声卡比较头疼， 尝试过几种方法， 还没搞定。 目前也没有看到成功的例子

**Comment by fzlee** [comment]
intel wifi稳定吗？ 貌似开关wifi需要用专门的工具？ 

声卡比较头疼， 尝试过几种方法， 还没搞定。 目前也没有看到成功的例子

**Comment by fengcms** [comment]
稳定还是稳定的，使用没有什么问题。我正常使用两天，没有出现断网的情况。是参考 http://bbs.pcbeta.com/viewthread-1848662-1-1.html 这篇帖子，使用的是 itlwm.kext 这个 kext 文件，外加它自带的 wifi 连接软件使用的。
暂时我是用蓝牙耳机来解决声音的问题，希望声卡的问题能早日解决，我对oc不熟，所以没深入研究。

**Comment by ansonliao** [comment]
我的主板一样， CPU是i5 10X00 ES (QSRK)
1. 
声卡驱动，前几天我用这个网友里面的EFI的KEXT是可以使用声卡的，但前天开始声卡突然不能又不行了，不知道为什么
http://bbs.pcbeta.com/forum.php?mod=viewthread&tid=1868070&highlight=b460m-itx

2. 
刚开始我也使用远景网友开发的intel wifi和蓝牙的补丁，不过我的情况是信号还是不如免驱卡稳定，掉线倒没出现过，只是有些软件老是提示说网络不稳定，大概估摸了下，信号跳跃还是比较大的。
最后还是换了免驱卡。

3. 
另外，请教 @fzlee , @fengcms 有睡眠时间比较长的话 (比如30分钟)唤醒后会没有视频信号输出到显示器的情况么? DP接口的，我试了下，手动睡眠，然后马上唤醒没问题，睡得时间长点就有点问题，我的BIOS是1.4版本

**Comment by fzlee** [comment]
我的是HDMI  + DP 两个接口都在使用。 
开机的时候HDMI 会花屏，DP是好的
在登陆界面会变成DP显示器黑屏， HDMI显示器正常。
输入密码之后DP依然黑屏， HDMI显示器会出现均匀的黑色横条。 
开关DP显示器之后两个显示器都会变的正常。


因为没有买独显， 可能是黑屏过对这个集成显卡的支持有问题（和仿冒device_id 有关？）

你的问题我好像没有遇到，前一天不关机， 第二天过来点击键盘或者鼠标， 貌似DP显示器是点亮的， HDMI则不会亮， 开关显示器正常

**Comment by fzlee** [comment]
貌似要打补丁？ 我懒得弄了
https://dortania.github.io/OpenCore-Install-Guide/extras/gpu-patches.html#mapping-video-ports

**Comment by ansonliao** [comment]
@fzlee 
欢迎界面DP接口黑屏这个，我之前也试过。
可能对妳有帮助。
我的显示器是LG 27UL600K，我之前的黑屏是通过把显示器的DP版本调成1.2，就解决了 (网上一外国也是和我一样的LG显示器，也是一样的黑屏)

不过我觉得欢迎界面在DP接口时黑屏，跟显示器应该有点关系，现在我这个B460M-ITX接在LG显示器上，DP版本1.2也是会黑屏，但我另一台黑果就不会。
后来我换了一个优派的VX2831的4K显示器，接在B460M-ITX上 (UHD630核显)就不会黑屏了。
这个比较奇怪。

妳可以参考一下。

**Comment by ansonliao** [comment]
@fzlee 
@fengcms 
请教你们的USB在hackintool下面会不会显示 `???` ？下面这样的，谢谢！
![image](https://user-images.githubusercontent.com/6060224/92118721-70195680-ee29-11ea-8101-cafb1eb56875.png)

**Comment by fzlee** [comment]
![Screen Shot 2020-09-04 at 08 57 16](https://user-images.githubusercontent.com/1934773/92187586-c4095700-ee8c-11ea-82bd-365dc147e0ad.png)

一样的

**Comment by ansonliao** [comment]
@fzlee 
USB这一部分挺奇怪的，不知道为什么显示是`???`的名称，还有当我使用`USBInjectAll.kext`时，我的USB3.0在hackintool下面是少了`SS01`这个的，隐隐地觉得，我睡眠唤醒黑屏问题可能跟usb有关。

一直觉得像我这样核显的用Macmini8,1去仿冒，在B460，10代CPU上有点缺陷。

**Comment by fzlee** [comment]
唤醒黑屏倒不是不可以接受， 反正睡醒开机开关一下显示器就好了。
USB的问题， 貌似USBInjectAll仅仅是一个临时的通用解决方案， 最后还是需要自己去修复一下映射的？
https://dortania.github.io/OpenCore-Post-Install/usb/#macos-and-the-15-port-limit

另外还有一个CFG-Lock的问题， 用来做电源控制的， 不知道有没有关系
https://dortania.github.io/OpenCore-Post-Install/misc/msr-lock.html#what-is-cfg-lock
官方文档的教程不适用我， 因为这个主板貌似没法`setup_var 0x5A4 0x00像这样在主板下修改cfg lock

**Comment by ansonliao** [comment]
1. 
我的唤醒黑屏，按开机键是解决不了，要重新开机才行，除非把睡眠关了。所以比较麻烦。

2. 
USBInjectAll是打所有的USB都打开，一般来说，后续还要定制每个usb的端口的。
我的USB在全部打开的状态下奇怪的地方是，b460m-itx这块板前面板2个USB3，后面板是4个USB3，总共是6个USB6，在Hackintool下面的USB显示，USB 2有"HS01，HS02，HS03，HS04，HS05，HS06"，这个数量是对得上的 (还有一个是蓝牙的HS09)，不过，USB 3的只有"SS02，SS03，SS04，SS05，SS06"，只有5个，少了一个。
这是奇怪的地方。

3. 
关于CFG-Lock，不是可以在BIOS里面关闭么?
我一直都是在BIOS里设置的，还有vt-d这个也可以在BIOS里面设置

**Comment by fzlee** [comment]
黑屏的问题我可能遇到过， 但是我的场景跟你不一样， 

我折腾过两个黑苹果， 另外一个是nuc， nuc貌似唤醒有一定概率会黑屏，插拔显示器数据线或者开关貌似也不能解决问题
关于这个b460m，我这边是两个1k显示器， 一般是睡眠后只有一个显示器亮屏， 我的问题至少并没有你提到的那么严重， 我这边如果唤醒等了一会儿另外一个显示器不能亮屏， 我至少可以开关一下显示器解决问题 。

CFG-Lock我指的是在主板解锁， 而不是在主板禁用。 解锁之后可以使用原生电源管理功能， 不知道你的跟这个有没有关系。

USBinjectAll的问题， 我不是很明白， 你看看我之前的hackintool的截图， 我也少了一个USB3吗？

最后， 你的SSDT-EC-USBX.aml补丁是哪里弄到的， 我这个是自己严格按照官方文档编译的， 你要不试试我的这个补丁， 说不定有些用处

**Comment by ansonliao** [comment]
1.
我另一个黑果是asrock z390 phantom gaming itx + i5 9600k + rx 5500 xt 8G的，这个倒是没有唤醒问题，现在来说这个黑果除了thunderbolt 3没去折腾外，一切都很完美 

不过这部黑果之前也碰过妳说的DP欢迎界面黑屏的问题，我的解决方案是把显示器的DP从1.4版本降到1.2版本。(这个解决方案对于我的b460m-itx无效)

2.
关于CFG-Lock，明白了，我也试试看能不能解决我的的DP唤醒黑屏的问题。
关于CFG-Lock，这个在另一个黑果上，我也只是在BIOS上禁用而已，也没有睡眠问题。

3. 
我看了妳的USB截图，妳的是完整的，所以我才觉得我的USB可能是有问题。

4. 
`SSDT-EC-USBX.aml` 我也是按照官方做的(opencore整个EFI都是按照官方做的，除了现在失效的声卡是别人的外)，晚上试试用妳的看有什么效果

**Comment by fengcms** [comment]
![20200904183821](https://user-images.githubusercontent.com/15262264/92230606-fa22f700-eedd-11ea-8aa3-b89dbc3e34bd.jpg)
我这边USB也是3个问号。
另外，今天蓝牙不能用了，比较郁闷。

**Comment by fzlee** [comment]
@fengcms 我感觉还是换我的那个网卡比较好， 不太贵， 换了就可以用

**Comment by fengcms** [comment]
![20200904184353](https://user-images.githubusercontent.com/15262264/92231015-9baa4880-eede-11ea-84e0-328531d62b84.jpg)

显示器倒是正常，没有黑屏过。睡眠都是正常的，睡一晚上第二天也是一碰就开了。

**Comment by fengcms** [comment]
@fzlee 你换的是哪块？方便发个淘宝链接不？

**Comment by fzlee** [comment]
BCM94352Z 去淘宝找找，， 不需要转换卡， 不需要额外驱动， 换了就可以用

**Comment by ansonliao** [comment]
@fengcms 
还是换免驱卡比较省事。
我用的是BCM94360CS2和BCM94360CD
我个人比较推荐BCM94360CD，不过这张卡如果是安装在主板上Intel的无线卡模块位置的话，原来的无线卡盒子会不够位置，还有就是天线要换，主板原来天线是4代的，BCM94360CD的天线是1代的，而且这张卡是4天线的，蓝牙是独立天线，信号干扰比较低。
如果PCIE位置有空余的话，可以买一张Fenvi的PCIE的BCM94360CD，我的机箱是迎广肖邦，有空余的PCIE也安装不了Fenvi的PCIE BCM94360CD。

BCM94360CS2这张卡除了要拆半边盒子外，尺寸完美兼容主板上的无线模块接口。

两张卡都不用放KEXT就可以完全使用。

**Comment by ansonliao** [comment]
@fengcms 
另外还有一张比较新的卡，博通的，但不是拆机卡，是华硕X99主板上自带的wifi go的无线蓝牙卡，在x鱼上有卖，型号是: BCM94360HMB
这卡也是免驱的。

**Comment by ansonliao** [comment]
@fzlee 
用MaciASL对比过你我的`SSDT-EC-USBX.aml`的代码是一样的，连行数都一样

**Comment by ansonliao** [comment]
@fzlee 
参考官方对核显打补丁的教程，我已经解决了睡眠唤醒DP黑屏的问题，https://dortania.github.io/OpenCore-Install-Guide/extras/gpu-patches.html#igpu-busid-patching

我把port 2为DP的接口关了，因为主板只有一个HDMI和DP接口
![image](https://user-images.githubusercontent.com/6060224/92329105-dc998d00-f097-11ea-8d25-ea366e59c187.png)

**Comment by fengcms** [comment]
@ansonliao 在闲鱼上买了一块 BCM94360HMB 今天到了，还没安装。今天早上开机，蓝牙又恢复了-_-|||，但是干扰依然在，使用蓝牙耳机会有杂音。我回头试试在windows系统上，看看有没有这个问题。不过暂时没安装windows，等回头有时间了折腾。

**Comment by fengcms** [comment]
@ansonliao 恭喜解决dp的问题，你也把 efi 发 github 上呀 :)

**Comment by ansonliao** [comment]
@fengcms 
哈哈，因为我已经很多年已经没有用windows了，下载手上的电脑也没有windows，所以我自己比较偏向于用免驱卡，毕竟intel无线模块在黑苹果上现在不是完善的。

就是因为没有windows所以定制不了这块主板声卡的 `AppleALC.KEXT` 和 `Lilu.KEXT` （我的SSD是Intel 760P，好像我这块SSD和Windows有兼容性问题，安装过好几次Windows都报碰到硬件问题）。

EFI我也打算完善后放到GayHub上，我发现我的usb似乎对USB 3的U盘读不到，解决了这个在放上来吧。

**Comment by fengcms** [comment]
@ansonliao 我刚换了这个朋友的EFI，貌似都好了呢。。。也期待有更完善的EFI。。。https://github.com/fzlee/B460M-ITX-AC-EFI/issues/2

**Comment by ansonliao** [comment]
@fzlee 
@fengcms 
我的USB 好了
现在看来，没有什么问题了，也没有 https://github.com/fzlee/B460M-ITX-AC-EFI/issues/2 这位朋友的闪烁问题

**Comment by fengcms** [comment]
@ansonliao 那就坐等你的EFI了哈

**Comment by fzlee** [comment]
问题已解决， 更新新版的代码即可， 注意三码还是需要使用你自己的。

**Comment by ansonliao** [comment]
@fzlee 
@fengcms 
我的EFI放在这里: https://github.com/ansonliao/Asrock-B460m-ITX-AC-OC-EFI
