### ISSUE TITLE
老哥后期会长时间更新吗  我这里有一份efi可以正常使用音频和原装的蓝牙wifi 如果有需要留个邮箱发给你吧.

### ISSUE THREAD

**Issue by chenwutong** [fzlee/B460M-ITX-AC-EFI#2]
在远景上找到的,自己已经安装上了,目前的使用来看就一个菜单栏输入法会闪烁的问题  不影响正常使用

**Comment by fengcms** [comment]
web@fengcms.com 期待邮件

**Comment by fzlee** [comment]
可以看看你的EFI吗， 不知道可不可以整合到这个项目里面来

**Comment by chenwutong** [comment]
> [web@fengcms.com](mailto:web@fengcms.com)期待邮件

已经发送了

**Comment by chenwutong** [comment]
> 可以看看你的EFI吗，不知道可不可以整合到这个项目里面来

[华擎b460itx-核显-dp-hdmi-EFI OC0.6.0.zip](https://github.com/fzlee/B460M-ITX-AC-EFI/files/5180824/b460itx-.-dp-hdmi-EFI.OC0.6.0.zip)

**Comment by ansonliao** [comment]
@chenwutong 
我也是用的这一份EFI里面的 `FakePCIID_Intel_HDMI_Audio.kext`，`FakePCIID.kext`，不过现在在我机器上已经不生效了

**Comment by fengcms** [comment]
@chenwutong 已经用上了，一切正常，音频也好使了。更让我讶异的是蓝牙耳机里，也没有杂音了，目前没发现有任何问题，中午测试一下睡眠。

**Comment by ansonliao** [comment]
@chenwutong 
我找到为什么 `FakePCIID_Intel_HDMI_Audio.kext`，`FakePCIID.kext` 之前失效的原因了，之前无意中把 `layout-id` 的类型设成了 `String`，现在改成正确的 `Data` 后，声卡正常了。
![image](https://user-images.githubusercontent.com/6060224/92347159-aa247a00-f101-11ea-9867-6b8864d4459a.png)

**Comment by chenwutong** [comment]
> @chenwutong已经用上了，一切正常，音频也好使了。更让我重复异的是蓝牙耳机里，也没有杂音了，目前没发现有任何问题，中午测试一下睡眠。

目前看来睡眠问题也不大 主要是efi的开发者貌似不愿意长时间维护 经过我测试更新就会出问题  我就一个小白 学习这个太困难了

**Comment by chenwutong** [comment]
> @chenwutong
> 我找到为什么 `FakePCIID_Intel_HDMI_Audio.kext`，`FakePCIID.kext` 之前失效的原因了，之前无意中把 `layout-id` 的类型设成了 `String`，现在改成正确的 `Data` 后，声卡正常了。
> ![image](https://user-images.githubusercontent.com/6060224/92347159-aa247a00-f101-11ea-9867-6b8864d4459a.png)

那目前看来作者的efi就没什么问题了  更换个蓝牙网卡就能正常使用了对吧

**Comment by ansonliao** [comment]
> > @chenwutong
> > 我找到为什么 `FakePCIID_Intel_HDMI_Audio.kext`，`FakePCIID.kext` 之前失效的原因了，之前无意中把 `layout-id` 的类型设成了 `String`，现在改成正确的 `Data` 后，声卡正常了。
> > ![image](https://user-images.githubusercontent.com/6060224/92347159-aa247a00-f101-11ea-9867-6b8864d4459a.png)
> 
> 那目前看来作者的efi就没什么问题了 更换个蓝牙网卡就能正常使用了对吧

他那个EFI很多我用不到的东西，所以我只用了他的FakePCIID_Intel_HDMI_Audio.kext，FakePCIID.kext而已，其它的都是我自己按照opencore官方教程做的。

如果你需要稳定的蓝牙和无线，要airdrop，handoff这些，就用免驱卡吧，如果不需要，用intel 无线蓝牙模块也行。

**Comment by chenwutong** [comment]
> > > @chenwutong 
> > > 我找到为什么`FakePCIID_Intel_HDMI_Audio.kext`，`FakePCIID.kext`之前失效的原因了，之前无意中把`layout-id`的类型设成`String`，现在改成正确的`Data`后，声卡正常了。
> > > ![图片](https://user-images.githubusercontent.com/6060224/92347159-aa247a00-f101-11ea-9867-6b8864d4459a.png)
> > 
> > 
> > 那目前看来作者的efi就没什么问题了更换个蓝牙网卡可以正常使用了对吧
> 
> 他那个EFI很多我用不到的东西，所以我只用了他的FakePCIID_Intel_HDMI_Audio.kext，FakePCIID.kext而已，其他的都是我自己按照opencore官方教程做的。
> 
> 如果您需要稳定的蓝牙和无线，要空投，移交这些，就用免驱卡吧，如果不需要，用intel无线蓝牙模块也行。

主要是我希望找到一个长期维护的efi来保证稳定和更新 如果作者不长时间使用出问题就很难进行维修 目前github还没有作者表示会长时间维护 这就很难受

**Comment by fengcms** [comment]
@chenwutong 好用就先用着呗，我也不会折腾着玩意儿。等过段时间再看，肯定就是百花齐放了。

**Comment by fzlee** [comment]
@chenwutong 谢谢， 我试了一下， 音频问题确实解决了

**Comment by fzlee** [comment]
@chenwutong 我这边应该会维护这个主板的EFI， 但是出于稳定性的考虑， 更新可能不会那么频繁。
你提供的补丁已经被我提交上去了

**Comment by ansonliao** [comment]
@fzlee 
@fengcms 
@chenwutong 
我的EFI放在这里: https://github.com/ansonliao/Asrock-B460m-ITX-AC-OC-EFI
