### ISSUE TITLE
Wifi

### ISSUE THREAD

**Issue by Arigun** [fzlee/B460M-ITX-AC-EFI#3]
I successfully installed my first hackintosh. Thank you. But I have a problem with my wifi, it’s not working.

**Comment by fzlee** [comment]
Onboard wifi is not supported. you may replace it with BCM94352Z, which works pretty well.

There is also a repo https://github.com/ansonliao/Asrock-B460m-ITX-AC-OC-EFI
which provides support for Intel Wifi.

**Comment by Arigun** [comment]
> I successfully installed my first hackintosh. Thank you. But I have a problem with my wifi, it’s not working.
