### ISSUE TITLE
BCM94352z在开启蓝牙连接了设备情况下，关机风扇一直转

### ISSUE THREAD

**Issue by yuraph** [fzlee/B460M-ITX-AC-EFI#6]

**Comment by yuraph** [comment]
补充一下，今天再次测试了一下，是蓝牙开启，并且并且连接了设备(比如蓝牙键盘、蓝牙鼠标)的情况，关机风扇才会一直转。

**Comment by fzlee** [comment]
我这边不能复现你的问题， 我的电脑硬件配置已经在文档里面列举出来了，在蓝牙鼠标连接的情况下， 关机风扇是不会运行的。

你有试过widnows系统下连接蓝牙关机吗， 个人感觉是不是主板或者是BIOS设置的问题

**Comment by yuraph** [comment]
windows下蓝牙连接了设备，关机正常关机。我再试试吧，然后再来反馈是否有问题。我的硬件配置和你差不多。主板、cpu、网卡都是一样的。

**Comment by yuraph** [comment]
@fzlee  另外，每次开机进入mac系统，都有大约10-20s的小卡顿，现象是，鼠标推动比正常时候慢，你们有这样的问题吗？

**Comment by fzlee** [comment]
个人感觉蓝牙鼠标有延迟应该是正常的， 你看看鼠标到机箱蓝牙天线之间是否有遮挡， 有遮挡的话说不定会导致延迟。

我的电脑开机并没有你说的卡顿。

**Comment by fzlee** [comment]
目前我这边除了连接两个显示器， 睡眠唤醒的时候需要手动开关某一个显示器， 不然显示不正常之外， 没有任何问题了。

你试试重置一下主板nvram？我这边目前没有别的建议了

**Comment by yuraph** [comment]
周末测试过了，有几点经验值
1.蓝牙连接情况下，关机风扇转的情况，通过clear nvram解决。
2.如果机型设置的mac mini，boot-args参数设置 
<string>igfxonln=1</string>
