### ISSUE TITLE
Wifi/ BT card

### ISSUE THREAD

**Issue by joshdesu** [fzlee/B460M-ITX-AC-EFI#7]
Thanks for your upload! I have very similar hardware except using the 10400. Using your EFI most things work except the wifi/bt card. Did you add anything extra to fix that or do you know which version of the BCM94352Z you have?
Thanks

**Comment by fzlee** [comment]
There is no big difference between 10400 and 10500.

I think BCM94352Z is supported out of the box. could there be something wrong your BCM94352Z?

**Comment by joshdesu** [comment]
There could possibly be, though I was able to get wifi working on it with Windows. Do you have a link for the one you used?

**Comment by fzlee** [comment]
https://item.taobao.com/item.htm?spm=a1z09.2.0.0.14762e8d7ofZYt&id=564499303977&_u=ij5h8k3cc74 

Price for my card is 278

**Comment by joshdesu** [comment]
Ok thanks, that looks like a similar card. I have tried with and without AirportBrcmFixup and BrcmPatchRAM. So might possibly buy from that source
