### ISSUE TITLE
不使用独立显卡的情况下，DP + HDMI  都是接显示器可以支持吗，谢谢

### ISSUE THREAD

**Issue by qq18436558** [fzlee/B460M-ITX-AC-EFI#8]
不使用独立显卡的情况下，DP + HDMI  都是接显示器可以支持吗，谢谢

**Comment by fzlee** [comment]
这个配置是支持双新显示器的， DP + HDMI。 但是直接连接会导致显示器屏幕出现奇怪的横条。
解决办法是关闭一台显示器， 过几秒钟再打开， 之后就好了

**Comment by qq18436558** [comment]
知道了，非常感谢，准备入手同样的配置
